# Generated by Django 3.1.8 on 2021-08-22 01:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_auto_20210814_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-22', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 22)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 22))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-22', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 22)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 22))]),
        ),
    ]
