# Generated by Django 3.1.8 on 2021-08-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='itemrequest',
            old_name='img',
            new_name='image',
        ),
    ]
