# Generated by Django 3.1.8 on 2021-08-23 06:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_auto_20210822_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-23', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 23)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 23))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-23', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 23)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 23))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
